cursor            #cabeff
cursor_text_color #31285f

foreground            #e6e1e9
background            #0f0d13
selection_foreground  #312e41
selection_background  #c9c3dc
url_color             #c9c3dc

#: black 000000 767676
color0  #141318
color8  #36343a
#: red cc0403 f2201f
color1  #0a090d
color9  #504966
#: green 19cb00 23fd00
color2  #c9c3dc
color10 #e6dff9
#: yellow cecb00 fffd00
color3  #edb8cc
color11 #ffd8e6
#: blue 0d73cc 1a8fff
color4  #483f77
color12 #cabeff
#: magenta cb1ed1 fd28ff
color5  #484459
color13 #c9c3dc
#: cyan 0dcdcd 14ffff
color6  #623b4c
color14 #edb8cc
#: white dddddd ffffff
color7  #c9c4d0
color15 #e6e1e9

mark1_foreground #1c1149
mark1_background #e6deff
mark2_foreground #1c192b
mark2_background #e6dff9
mark3_foreground #301120
mark3_background #ffd8e6

active_tab_foreground #31285f
active_tab_background #cabeff
inactive_tab_foreground #e6deff
inactive_tab_background #483f77

active_border_color #cabeff
inactive_border_color #31285f
# bell_border_color #ff5a00
