color0 #131313
color1 #ffb4ab
color2 #7ad0ff
color3 #b5c9d7
color4 #cac1ea
color5 #7ad0ff
color6 #b5c9d7
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #7ad0ff
color11 #b5c9d7
color12 #cac1ea
color13 #7ad0ff
color14 #b5c9d7
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #7ad0ff
inactive_border_color #474747
url_color             #7ad0ff

active_tab_foreground   #003549
active_tab_background   #7ad0ff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
