# --- Key bindings ---

# Session

bind = SUPER+SHIFT, R, reload_config

# I got screenshots working properly :3
bind = NONE, Print, spawn, grim - | wl-copy
bind = SUPER, Print, spawn, grim -g "$(slurp -d)" - | wl-copy

bind = SUPER, T, spawn, bash "$HOME/.config/scripts/wofi-wallpaper-switcher.sh"

# Window

bind = SUPER, Q, killclient
bind = SUPER, F, togglefullscreen

bind = SUPER, Return, spawn, kitty
bind = SUPER,  Space, spawn, qs -c noctalia-shell ipc call launcher toggle

# Focus & movement

bind = SUPER, h, focusdir, left
bind = SUPER, j, focusdir, down
bind = SUPER, k, focusdir, up
bind = SUPER, l, focusdir, right

bind = SUPER+SHIFT, h, exchange_client, left
bind = SUPER+SHIFT, j, exchange_client, down
bind = SUPER+SHIFT, k, exchange_client, up
bind = SUPER+SHIFT, l, exchange_client, right

# Tags / workspaces

bind = SUPER, Tab, viewtoright_have_client
bind = SUPER+SHIFT, Tab, viewtoleft_have_client

bind = SUPER, 1, view, 1
bind = SUPER, 2, view, 2
bind = SUPER, 3, view, 3
bind = SUPER, 4, view, 4
bind = SUPER, 5, view, 5

bind = SUPER+SHIFT, 1, tag, 1
bind = SUPER+SHIFT, 2, tag, 2
bind = SUPER+SHIFT, 3, tag, 3
bind = SUPER+SHIFT, 4, tag, 4
bind = SUPER+SHIFT, 5, tag, 5

# Layouts

bind = SUPER, w, switch_layout

# Brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 0%

# Volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# Playback
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause

# --- Mouse & Gestures ---

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

gesturebind = NONE, left, 3, viewtoright_have_client
gesturebind = NONE, right, 3, viewtoleft_have_client

gesturebind = NONE, up, 3, toggleoverview
