source=./colors.conf

# Environment variables

env = QT_QPA_PLATFORM, wayland
env = QT_QPA_PLATFORMTHEME, qt6ct

# Autostart

exec-once=mako
exec-once=mpd
exec-once=qs
exec-once=waybar
exec-once=awww-daemon
exec-once=wlsunset -l 60.0 -L -3.2

# Input devices
xkb_rules_layout=gb
xkb_rules_options=compose:caps-altgr
trackpad_natural_scrolling=1

source=./theme.conf
source=./binds.conf

exec=notify-send "Reloaded mango config"
