# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0x7ad0ffff
maximizescreencolor = 0xb5c9d7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xcac1eaff
globalcolor = 0x004c68ff
overlaycolor = 0x364955ff
