# --- Theming ---

borderpx = 2

# Cursor theme

cursor_size = 24
cursor_theme = Bibata-Modern-Classic

# --- Window effects ---

# Opacity & corner radius

blur = 1
blur_params_radius = 8
blur_params_num_passes = 2
border-radius = 15

